### ISSUE TITLE
will the pusher work in offline?

### ISSUE THREAD

**Issue by Iamasthme** [pusher/android-slack-clone#2]
i could see that message can be fetched by remote. what about the existing  previous messages? will it work in offline

**Comment by pablisco** [comment]
There is an imminent release for https://github.com/pusher/chatkit-android planned (no dates yet). The documentation for the new version is on the main `README.md`. In the meantime, you can download the repo and build it locally. Any feedback is more than welcomed.

Offline support is not supported out of the box. I would suggest wrapping the SDK into a component to support offline. We are also happy to accept PRs that may improve the product.
